/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package khaslanainventaris;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafidhp
 */
public class DeleteItemFrame extends javax.swing.JDialog {
    connection dbConn;
    private MainMenu parent;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeleteItemFrame.class.getName());
    
    private void loadDataTable() {
        try {
            String query = "SELECT * FROM items";
            
            PreparedStatement ps = dbConn.conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = new DefaultTableModel();
            
            model.addColumn("ID");
            model.addColumn("Nama Item");
            
            while (rs.next()) {
                model.addRow(new Object[] {
                    rs.getInt("id"),
                    rs.getString("name"),
                });
            }
            dataTable.setModel(model);
            
            rs.close();
            ps.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Gagal memuat data\n" + e.getMessage()
            );
        }
    }

    /**
     * Creates new form DeleteCategoryDialog
     */
    public DeleteItemFrame(java.awt.Frame frame, MainMenu parent, boolean modal) {
        super(frame, modal);
        initComponents();
        getContentPane().setBackground(new Color(30, 27, 38));
        setLocationRelativeTo(null);
        dbConn = new connection();
        loadDataTable();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idNameField = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Google Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 51));
        jLabel1.setText("Khaslana Inventaris");

        jLabel2.setFont(new java.awt.Font("Google Sans", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hapus Item");

        jLabel3.setFont(new java.awt.Font("Google Sans", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID atau Nama Item");

        idNameField.setBackground(new java.awt.Color(30, 27, 38));
        idNameField.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        idNameField.setForeground(new java.awt.Color(255, 255, 255));
        idNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 51), 1, true));
        idNameField.addActionListener(this::idNameFieldActionPerformed);

        deleteBtn.setBackground(new java.awt.Color(204, 51, 0));
        deleteBtn.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Hapus");
        deleteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 1, true));
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 51), 1, true));

        dataTable.setBackground(new java.awt.Color(30, 27, 38));
        dataTable.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        dataTable.setForeground(new java.awt.Color(255, 255, 255));
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        dataTable.setGridColor(new java.awt.Color(153, 255, 51));
        jScrollPane1.setViewportView(dataTable);

        jLabel4.setFont(new java.awt.Font("Google Sans", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data Item Saat Ini");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idNameFieldActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String input = idNameField.getText().trim();
        
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID atau Nama Item harus diisi!");
            return;
        }
        
        try {
            String query;

            if (input.matches("\\d+")) {
                query = "DELETE FROM items WHERE id = ?";
            } else {
                query = "DELETE FROM items WHERE name = ?";
            }
            
            PreparedStatement ps = dbConn.conn.prepareStatement(query);

            if (input.matches("\\d+")) {
                ps.setInt(1, Integer.parseInt(input));
            } else {
                ps.setString(1, input);
            }

            int affectedRows = ps.executeUpdate();

            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this, "Item berhasil dihapus!");
                parent.refreshData();
                loadDataTable();
                idNameField.setText(null);
            } else {
                JOptionPane.showMessageDialog(this, "Item tidak ditemukan!");
            }
            ps.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Gagal menghapus item\n" + e.getMessage()
            );
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dataTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField idNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
