/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package khaslanainventaris;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Kyuzuki
 */
public class EditItemDialog extends javax.swing.JDialog {
    
    MainMenu mainMenu;
    connection dbConn;
    int currentItemId;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditItemDialog.class.getName());

    /**
     * Creates new form EditItemDialog
     */
    public EditItemDialog(java.awt.Frame parent, boolean modal, int itemId) {
        super(parent, modal);
        initComponents();
        
        this.mainMenu = (MainMenu) parent;
        this.dbConn = new connection();
        this.currentItemId = itemId;
        
        jButtonBatal.addActionListener(this::jButtonBatalActionPerformed);
        
        loadDataToForm();
    }
    
    private void loadDataToForm() {
        try {
            
            jComboBoxKategori.removeAllItems();
            
            if (dbConn == null || dbConn.conn == null) {
                JOptionPane.showMessageDialog(this, "Koneksi database tidak tersedia!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            ResultSet rsKategori = dbConn.conn.createStatement().executeQuery("SELECT * FROM categories");
            int jumlahKategori = 0;
            while (rsKategori.next()) {
                jComboBoxKategori.addItem(rsKategori.getString("name"));
                jumlahKategori++;
            }
            rsKategori.close();

            if (jumlahKategori == 0) {
                JOptionPane.showMessageDialog(this, "Peringatan: Tidak ada data kategori ditemukan di database! Silakan tambah kategori terlebih dahulu.", "Database Kosong", JOptionPane.WARNING_MESSAGE);
            }

            jComboBoxKondisi.removeAllItems();
            jComboBoxKondisi.addItem("BAIK");
            jComboBoxKondisi.addItem("KURANG BAIK");
            jComboBoxKondisi.addItem("RUSAK");

            String query = """
                SELECT i.*, c.name as category_name 
                FROM items i 
                LEFT JOIN categories c ON i.category_id = c.id 
                WHERE i.id = ?
            """;
            PreparedStatement ps = dbConn.conn.prepareStatement(query);
            ps.setInt(1, currentItemId);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                
                jTextFieldBarang.setText(rs.getString("name"));
                jTextFieldKodeBarang.setText(rs.getString("code"));
                jSpinnerJumlah.setValue(rs.getInt("jumlah"));
                jTextFieldCatatan.setText(rs.getString("notes"));
                
                if (rs.getString("category_name") != null) {
                    jComboBoxKategori.setSelectedItem(rs.getString("category_name"));
                }
                if (rs.getString("item_condition") != null) {
                    jComboBoxKondisi.setSelectedItem(rs.getString("item_condition"));
                }
            } else {
                JOptionPane.showMessageDialog(this, "Data barang dengan ID " + currentItemId + " tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            rs.close();
            ps.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data di form: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jTextFieldBarang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxKategori = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldKodeBarang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSpinnerJumlah = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxKondisi = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCatatan = new javax.swing.JTextField();
        jButtonBatal = new javax.swing.JButton();
        jButtonSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDIT BARANG");
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel.setBackground(new java.awt.Color(0, 0, 0));
        jPanel.setForeground(new java.awt.Color(0, 0, 0));

        jTextFieldBarang.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldBarang.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jTextFieldBarang.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama Barang :");

        jLabel9.setFont(new java.awt.Font("Google Sans", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 0));
        jLabel9.setText("EDIT DATA BARANG");

        jLabel10.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Kategori           :");

        jComboBoxKategori.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxKategori.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jComboBoxKategori.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxKategori.addActionListener(this::jComboBoxKategoriActionPerformed);

        jLabel11.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kode Barang  :");

        jTextFieldKodeBarang.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldKodeBarang.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jTextFieldKodeBarang.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldKodeBarang.addActionListener(this::jTextFieldKodeBarangActionPerformed);

        jLabel12.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jumlah             :");

        jSpinnerJumlah.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Kondisi             :");

        jComboBoxKondisi.setBackground(new java.awt.Color(51, 51, 51));
        jComboBoxKondisi.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jComboBoxKondisi.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxKondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxKondisi.addActionListener(this::jComboBoxKondisiActionPerformed);

        jLabel14.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Catatan(ops.) :");

        jTextFieldCatatan.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldCatatan.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jTextFieldCatatan.setForeground(new java.awt.Color(255, 255, 255));

        jButtonBatal.setBackground(new java.awt.Color(255, 0, 0));
        jButtonBatal.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jButtonBatal.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBatal.setText("Batal");
        jButtonBatal.addActionListener(this::jButtonBatalActionPerformed);

        jButtonSimpan.setBackground(new java.awt.Color(0, 255, 51));
        jButtonSimpan.setFont(new java.awt.Font("Google Sans", 0, 12)); // NOI18N
        jButtonSimpan.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSimpanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jButtonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(3, 3, 3)))
                        .addGap(19, 19, 19)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCatatan)
                            .addComponent(jTextFieldKodeBarang)
                            .addComponent(jTextFieldBarang)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)))))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addGap(32, 32, 32)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBoxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jSpinnerJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13)
                    .addComponent(jComboBoxKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCatatan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jComboBoxKondisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKondisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxKondisiActionPerformed

    private void jTextFieldKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKodeBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKodeBarangActionPerformed

    private void jButtonSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimpanMouseClicked
        // TODO add your handling code here:
        try {

            if (jTextFieldBarang.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Nama barang tidak boleh kosong!");
                return;
            }

            if (jTextFieldKodeBarang.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Kode barang tidak boleh kosong!");
                return;
            }

            if (jComboBoxKategori.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this,
                        "Silakan pilih kategori terlebih dahulu!");
                return;
            }

            String namaKategori
                    = jComboBoxKategori.getSelectedItem().toString();

            PreparedStatement psKat
                    = dbConn.conn.prepareStatement(
                            "SELECT id FROM categories WHERE name=?");

            psKat.setString(1, namaKategori);

            ResultSet rsKat = psKat.executeQuery();

            int idKategori = 0;

            if (rsKat.next()) {
                idKategori = rsKat.getInt("id");
            }

            rsKat.close();
            psKat.close();

            String query
                    = "UPDATE items SET "
                    + "name=?, "
                    + "category_id=?, "
                    + "code=?, "
                    + "jumlah=?, "
                    + "item_condition=?, "
                    + "notes=? "
                    + "WHERE id=?";

            PreparedStatement ps
                    = dbConn.conn.prepareStatement(query);

            ps.setString(1,
                    jTextFieldBarang.getText().trim());

            ps.setInt(2,
                    idKategori);

            ps.setString(3,
                    jTextFieldKodeBarang.getText().trim());

            ps.setInt(4,
                    Integer.parseInt(
                            jSpinnerJumlah.getValue().toString()));

            ps.setString(5,
                    jComboBoxKondisi.getSelectedItem().toString());

            ps.setString(6,
                    jTextFieldCatatan.getText().trim());

            ps.setInt(7,
                    currentItemId);

            int result = ps.executeUpdate();

            ps.close();

            if (result > 0) {

                JOptionPane.showMessageDialog(
                        this,
                        "Barang berhasil diupdate!");

                mainMenu.refreshData();

                dispose();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Data tidak berhasil diupdate!");

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Gagal update data:\n" + e.getMessage());

            e.printStackTrace();

        }
    }//GEN-LAST:event_jButtonSimpanMouseClicked

    private void jComboBoxKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxKategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                EditItemDialog dialog = new EditItemDialog(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JComboBox<String> jComboBoxKategori;
    private javax.swing.JComboBox<String> jComboBoxKondisi;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel;
    private javax.swing.JSpinner jSpinnerJumlah;
    private javax.swing.JTextField jTextFieldBarang;
    private javax.swing.JTextField jTextFieldCatatan;
    private javax.swing.JTextField jTextFieldKodeBarang;
    // End of variables declaration//GEN-END:variables
}
